apiVersion: v1
kind: Secret
metadata:
  name: python-fixture
stringData:
  slack_bot_token: xoxb-321654987012-TFA2026PYTHONBOT-abcdefghijklmnopqrstuvwx
  jwt_secret: tfa-python-jwt-signing-secret-2026
