apiVersion: v1
kind: Secret
metadata:
  name: ruby-fixture
stringData:
  github_pat: github_pat_11RBAABBCCDDEEFF00112233445566778899aabbccddeeff
  slack_bot_token: xoxb-147258369000-TFA2026RUBYBOT-abcdefghijklmnopqrstuvwx
