apiVersion: v1
kind: Secret
metadata:
  name: kotlin-fixture
stringData:
  jwt_secret: tfa-kotlin-jwt-signing-secret-2026
  slack_bot_token: xoxb-258147369000-TFA2026KOTLINBOT-abcdefghijklmnopqrstuvwx
