apiVersion: v1
kind: Secret
metadata:
  name: csharp-fixture
stringData:
  slack_bot_token: xoxb-753159456000-TFA2026CSHARPBOT-abcdefghijklmnopqrstuvwx
  jwt_secret: tfa-csharp-jwt-signing-secret-2026
